-- MySQL Script generated by MySQL Workbench
-- Mon Jul 12 17:30:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzería
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzería` ;

-- -----------------------------------------------------
-- Schema Pizzería
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzería` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Pizzería
-- -----------------------------------------------------
USE `Pizzería` ;

-- -----------------------------------------------------
-- Table `Pizzería`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`provincia` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`provincia` (
  `idprovincia` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`localidad` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`localidad` (
  `idlocalidad` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`idlocalidad`),
  INDEX `fk_localidad_provincia1_idx` (`provincia_idprovincia` ASC),
  CONSTRAINT `fk_localidad_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `Pizzería`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`cliente` (
  `idcliente` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `provincia_idprovincia` INT NOT NULL,
  `localidad_idlocalidad` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_provincia1_idx` (`provincia_idprovincia` ASC),
  INDEX `fk_cliente_localidad1_idx` (`localidad_idlocalidad` ASC),
  CONSTRAINT `fk_cliente_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `Pizzería`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_localidad1`
    FOREIGN KEY (`localidad_idlocalidad`)
    REFERENCES `Pizzería`.`localidad` (`idlocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`pedidos` (
  `idpedidos` INT NOT NULL auto_increment,
  `fecha_hora` DATETIME NULL,
  `tipo_pedido` VARCHAR(45) NULL,
  `cantidad_categoria` INT NULL,
  `precio_total` FLOAT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_cliente1_idx` (`cliente_idcliente` ASC) ,
  CONSTRAINT `fk_pedidos_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `Pizzería`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`tipo` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`tipo` (
  `idtipo` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`categoria_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`categoria_pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`categoria_pizza` (
  `idcategoria_pizza` INT NOT NULL auto_increment, 
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`productos` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`productos` (
  `idproductos` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `imagen` BLOB NULL,
  `precio` FLOAT NULL,
  `tipo_idtipo` INT NOT NULL,
  `categoria_pizza_idcategoria_pizza` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_tipo1_idx` (`tipo_idtipo` ASC),
  INDEX `fk_productos_categoria_pizza1_idx` (`categoria_pizza_idcategoria_pizza` ASC),
  CONSTRAINT `fk_productos_tipo1`
    FOREIGN KEY (`tipo_idtipo`)
    REFERENCES `Pizzería`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categoria_pizza1`
    FOREIGN KEY (`categoria_pizza_idcategoria_pizza`)
    REFERENCES `Pizzería`.`categoria_pizza` (`idcategoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`pedidos_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`pedidos_has_productos` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`pedidos_has_productos` (
  `pedidos_idpedidos` INT NOT NULL auto_increment,
  `productos_idproductos` INT NOT NULL,
  PRIMARY KEY (`pedidos_idpedidos`, `productos_idproductos`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`productos_idproductos` ASC),
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`pedidos_idpedidos` ASC),
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `Óptica`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `Pizzería`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`tienda` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`tienda` (
  `idtienda` INT NOT NULL auto_increment,
  `CP` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `localidad_idlocalidad` INT NOT NULL,
  PRIMARY KEY (`idtienda`),
  INDEX `fk_tienda_localidad1_idx` (`localidad_idlocalidad` ASC),
  CONSTRAINT `fk_tienda_localidad1`
    FOREIGN KEY (`localidad_idlocalidad`)
    REFERENCES `Pizzería`.`localidad` (`idlocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`categoria_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`categoria_empleado` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`categoria_empleado` (
  `idcategoria_empleado` INT NOT NULL auto_increment,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzería`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzería`.`empleados` ;

CREATE TABLE IF NOT EXISTS `Pizzería`.`empleados` (
  `idempleados` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `categoria_empleado_idcategoria_empleado` INT NOT NULL,
  `tienda_idtienda` INT NOT NULL,
  PRIMARY KEY (`idempleados`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC),
  INDEX `fk_empleados_categoria_empleado1_idx` (`categoria_empleado_idcategoria_empleado` ASC),
  INDEX `fk_empleados_tienda1_idx` (`tienda_idtienda` ASC),
  CONSTRAINT `fk_empleados_categoria_empleado1`
    FOREIGN KEY (`categoria_empleado_idcategoria_empleado`)
    REFERENCES `Pizzería`.`categoria_empleado` (`idcategoria_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_tienda1`
    FOREIGN KEY (`tienda_idtienda`)
    REFERENCES `Pizzería`.`tienda` (`idtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
