-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 14:10:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `youtube` ;

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8mb4 ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`usuario` ;

CREATE TABLE IF NOT EXISTS `youtube`.`usuario` (
  `idusuario` INT(11) NOT NULL auto_increment,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NULL DEFAULT NULL,
  `pais` VARCHAR(20) NULL DEFAULT NULL,
  `cp` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`canal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`canal` ;

CREATE TABLE IF NOT EXISTS `youtube`.`canal` (
  `idcanal` INT(11) NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcanal`),
  INDEX `fk_canal_usuario` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_canal_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`videos` ;

CREATE TABLE IF NOT EXISTS `youtube`.`videos` (
  `idvideos` INT(11) NOT NULL auto_increment,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `tamaño` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `duracion` VARCHAR(45) NULL DEFAULT NULL,
  `thumbnail` BLOB NULL DEFAULT NULL,
  `reproducciones` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_hora_publicacion` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idvideos`),
  INDEX `fk_videos_usuario` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_videos_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `youtube`.`comentarios` (
  `idcomentarios` INT(11) NOT NULL auto_increment,
  `texto` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `videos_idvideos` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_videos` (`videos_idvideos` ASC) ,
  INDEX `fk_comentarios_usuario` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_comentarios_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_videos`
    FOREIGN KEY (`videos_idvideos`)
    REFERENCES `youtube`.`videos` (`idvideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`comentarios_vistos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`comentarios_vistos` ;

CREATE TABLE IF NOT EXISTS `youtube`.`comentarios_vistos` (
  `idcomentarios_vistos` INT(11) NOT NULL auto_increment,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `comentarios_idcomentarios` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentarios_vistos`),
  INDEX `fk_comentarios_vistos_comentarios` (`comentarios_idcomentarios` ASC),
  CONSTRAINT `fk_comentarios_vistos_comentarios`
    FOREIGN KEY (`comentarios_idcomentarios`)
    REFERENCES `youtube`.`comentarios` (`idcomentarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`dislikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`dislikes` ;

CREATE TABLE IF NOT EXISTS `youtube`.`dislikes` (
  `iddislikes` INT(11) NOT NULL auto_increment,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `videos_idvideos` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`iddislikes`),
  INDEX `fk_dislikes_videos` (`videos_idvideos` ASC) ,
  INDEX `fk_dislikes_usuario` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_dislikes_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dislikes_videos`
    FOREIGN KEY (`videos_idvideos`)
    REFERENCES `youtube`.`videos` (`idvideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`etiquetas` ;

CREATE TABLE IF NOT EXISTS `youtube`.`etiquetas` (
  `idetiquetas` INT(11) NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `videos_idvideos` INT(11) NOT NULL,
  PRIMARY KEY (`idetiquetas`),
  INDEX `fk_etiquetas_videos` (`videos_idvideos` ASC) ,
  CONSTRAINT `fk_etiquetas_videos`
    FOREIGN KEY (`videos_idvideos`)
    REFERENCES `youtube`.`videos` (`idvideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`likes` ;

CREATE TABLE IF NOT EXISTS `youtube`.`likes` (
  `idlikes` INT(11) NOT NULL auto_increment,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `videos_idvideos` INT(11) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idlikes`),
  INDEX `fk_likes_videos` (`videos_idvideos` ASC) ,
  INDEX `fk_likes_usuario` (`usuario_idusuario` ASC) ,
  CONSTRAINT `fk_likes_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_videos`
    FOREIGN KEY (`videos_idvideos`)
    REFERENCES `youtube`.`videos` (`idvideos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `youtube`.`playlist` ;

CREATE TABLE IF NOT EXISTS `youtube`.`playlist` (
  `idplaylist` INT(11) NOT NULL auto_increment,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idplaylist`),
  INDEX `fk_playlist_usuario` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_playlist_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `youtube`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
