-- MySQL Script generated by MySQL Workbench
-- Mon Jul 12 17:37:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Óptica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Óptica` ;

-- -----------------------------------------------------
-- Schema Óptica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Óptica` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema Pizzería
-- -----------------------------------------------------
USE `Óptica` ;

-- -----------------------------------------------------
-- Table `Óptica`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`Proveedor` (
  `Id` INT NOT NULL,
  `telefono` VARCHAR(9) NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `puerta` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `CP` INT NULL,
  `pais` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`marca` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`marca` (
  `idmarca` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Proveedor_Id` INT NOT NULL,
  PRIMARY KEY (`idmarca`),
  INDEX `fk_marca_Proveedor1_idx` (`Proveedor_Id` ASC) VISIBLE,
  CONSTRAINT `fk_marca_Proveedor1`
    FOREIGN KEY (`Proveedor_Id`)
    REFERENCES `Óptica`.`Proveedor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`tipo_montura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`tipo_montura` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`tipo_montura` (
  `idtipo_montura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_montura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`Clientes` (
  `id` INT NOT NULL,
  `telefono` VARCHAR(9) NULL,
  `direccion` VARCHAR(100) NULL,
  `fecha_registro` DATE NULL,
  `email` VARCHAR(45) NULL,
  `id_recomendado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clientes_Clientes1_idx` (`id_recomendado` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Clientes1`
    FOREIGN KEY (`id_recomendado`)
    REFERENCES `Óptica`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`empleado` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`empleado` (
  `idempleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Óptica`.`Gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Óptica`.`Gafas` ;

CREATE TABLE IF NOT EXISTS `Óptica`.`Gafas` (
  `id_gafas` INT NOT NULL,
  `precio` FLOAT NULL,
  `graduacion_izquierda` FLOAT NOT NULL,
  `graduacion_derecha` FLOAT NOT NULL,
  `montura` VARCHAR(45) NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_izquierda` VARCHAR(45) NULL,
  `color_derecha` VARCHAR(45) NULL,
  `marca_idmarca` INT NOT NULL,
  `tipo_montura_idtipo_montura` INT NOT NULL,
  `Clientes_id` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `fk_Gafas_marca1_idx` (`marca_idmarca` ASC) VISIBLE,
  INDEX `fk_Gafas_tipo_montura1_idx` (`tipo_montura_idtipo_montura` ASC) VISIBLE,
  INDEX `fk_Gafas_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  INDEX `fk_Gafas_empleado1_idx` (`empleado_idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_Gafas_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `Óptica`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_tipo_montura1`
    FOREIGN KEY (`tipo_montura_idtipo_montura`)
    REFERENCES `Óptica`.`tipo_montura` (`idtipo_montura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `Óptica`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gafas_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `Óptica`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
