INSERT INTO tiendas (name, capacidad_Maxima) VALUES ('Tienda1', 350);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda2', 125);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda3', 654);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda4', 45);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda5', 875);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda6', 89);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda7', 9);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda8', 456);
INSERT INTO TIENDAS (name, capacidad_Maxima) VALUES ('Tienda9', 4543);

INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', null, 2005.3, (CURRENT_TIMESTAMP), 1);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', null, 2005.3, (CURRENT_TIMESTAMP), 1);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', 'Picasso', 1205.2, (CURRENT_TIMESTAMP), 1);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', 'Van Gogh', 34005.3, (CURRENT_TIMESTAMP), 1);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Reflejos', null, 5505,(CURRENT_TIMESTAMP), 2);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Noche estrellada', 'Coronado', 7705, (CURRENT_TIMESTAMP), 2);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Los jugadores de cartas', 'PAUL CÉZANNE', 10543, (CURRENT_TIMESTAMP), 2);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Autorretrato', 'REMBRANDT VAN RIJN', 25233, (CURRENT_TIMESTAMP), 3);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', null, 78675, (CURRENT_TIMESTAMP), 3);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Autorretrato con boina', 'CLAUDE MONET', 974564, (CURRENT_TIMESTAMP), 3);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'ASDADWAD', null, 4534534, (CURRENT_TIMESTAMP), 4);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'awiodjawoid', 'WASSILY KANDINSKY', 346346,(CURRENT_TIMESTAMP), 4);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Las Meninas', 'DIEGO VELAZQUEZ', 123144, (CURRENT_TIMESTAMP), 4);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'iqweiqw', null, 234234, (CURRENT_TIMESTAMP), 5);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Gioconda', 'Leonardo da Vinci', 765756, (CURRENT_TIMESTAMP), 5);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'AWDADOI', null, 12342, (CURRENT_TIMESTAMP), 5);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ('Soledad', null, 236544, (CURRENT_TIMESTAMP), 6);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', 'GIOTTO DI BONDONE', 657556, (CURRENT_TIMESTAMP), 6);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', null, 34234, (CURRENT_TIMESTAMP), 6);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Soledad', null, 453534, (CURRENT_TIMESTAMP), 7);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'qpwioeqp', 'TURNER', 23434.3, (CURRENT_TIMESTAMP), 7);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'piqowepqw', 'CARAVAGGIO', 11111, (CURRENT_TIMESTAMP), 7);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Alegria', null, 43534.4, (CURRENT_TIMESTAMP), 8);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'Tristeza', 'VAN EYCK', 234324, (CURRENT_TIMESTAMP), 8);
INSERT INTO COLLARES(name, author, price, arrival, tienda_id) VALUES ( 'awiduaw', null, 345345.3, (CURRENT_TIMESTAMP), 8);